/* Generated by MyraPad at Mon, 08. 05. 2023 13  :  00  :  12 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace ANXY
{
	partial class background: Panel
	{
		private void BuildUI()
		{
			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Background = new SolidBrush("#0000FFFF");

			
			Widgets.Add(horizontalStackPanel1);
		}

		
	}
}
