/* Generated by MyraPad at Tue, 09. 05. 2023 00  :  41  :  22 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace ANXY
{
	partial class FPS: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "FPS";
			label1.TextColor = ColorStorage.CreateColor(254, 57, 48, 255);

			
			Widgets.Add(label1);
		}

		
	}
}
