/* Generated by MyraPad at Mon, 05. 06. 2023 19  :  26  :  36 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace ANXY.UI
{
	partial class GameOverlay: Grid
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "current FPS: 2000.09";
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var label2 = new Label();
			label2.Text = "Min: 100.09";
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var label3 = new Label();
			label3.Text = "Max: 6000.12";
			label3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var label4 = new Label();
			label4.Text = "FPS refreshing every 0.33s";

			var label5 = new Label();
			label5.Text = "Min/Max refreshing every 2s";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 2;
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			verticalStackPanel1.Padding = new Thickness(5);
			verticalStackPanel1.Background = new SolidBrush("#000000DD");
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(label2);
			verticalStackPanel1.Widgets.Add(label3);
			verticalStackPanel1.Widgets.Add(label4);
			verticalStackPanel1.Widgets.Add(label5);

			var label6 = new Label();
			label6.Text = "Debuggin Mode";
			label6.Padding = new Thickness(0, 0, 0, 7);
			label6.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label7 = new Label();
			label7.Text = "XY: 12.59 / 34.90";
			label7.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label8 = new Label();
			label8.Text = "Facing: Right";
			label8.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label9 = new Label();
			label9.Text = "Midair: false";
			label9.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label10 = new Label();
			label10.Text = "Toggle Hitboxes with F6";
			label10.Padding = new Thickness(0, 7, 0, 0);
			label10.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalStackPanel2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			verticalStackPanel2.Padding = new Thickness(5);
			verticalStackPanel2.GridColumn = 1;
			verticalStackPanel2.Background = new SolidBrush("#FF0000DD");
			verticalStackPanel2.Widgets.Add(label6);
			verticalStackPanel2.Widgets.Add(label7);
			verticalStackPanel2.Widgets.Add(label8);
			verticalStackPanel2.Widgets.Add(label9);
			verticalStackPanel2.Widgets.Add(label10);

			var label11 = new Label();
			label11.Text = "12:34:56.78";
			label11.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var label12 = new Label();

			var label13 = new Label();
			label13.Text = "Fastest time:";
			label13.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var label14 = new Label();
			label14.Text = "12:34:56.78";
			label14.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var verticalStackPanel3 = new VerticalStackPanel();
			verticalStackPanel3.Spacing = 2;
			verticalStackPanel3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			verticalStackPanel3.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			verticalStackPanel3.Padding = new Thickness(5);
			verticalStackPanel3.GridColumn = 2;
			verticalStackPanel3.Background = new SolidBrush("#000000AA");
			verticalStackPanel3.Widgets.Add(label11);
			verticalStackPanel3.Widgets.Add(label12);
			verticalStackPanel3.Widgets.Add(label13);
			verticalStackPanel3.Widgets.Add(label14);

			var label15 = new Label();
			label15.Text = "ANXY";
			label15.Padding = new Thickness(0, 0, 0, 4);
			label15.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label15.Scale = new Vector2();

			var label16 = new Label();
			label16.Text = "Welcome to";
			label16.Padding = new Thickness(0, 0, 0, 3);
			label16.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label16.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			var label17 = new Label();

			var label18 = new Label();
			label18.Text = "Move with A & D";
			label18.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label19 = new Label();
			label19.Text = "Jump with Space";
			label19.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label20 = new Label();
			label20.Text = "Open the Menu with ESC";
			label20.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var verticalStackPanel4 = new VerticalStackPanel();
			verticalStackPanel4.Spacing = 2;
			verticalStackPanel4.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalStackPanel4.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalStackPanel4.Padding = new Thickness(5);
			verticalStackPanel4.GridColumn = 1;
			verticalStackPanel4.GridRow = 1;
			verticalStackPanel4.Background = new SolidBrush("#000000AA");
			verticalStackPanel4.Widgets.Add(label15);
			verticalStackPanel4.Widgets.Add(label16);
			verticalStackPanel4.Widgets.Add(label17);
			verticalStackPanel4.Widgets.Add(label18);
			verticalStackPanel4.Widgets.Add(label19);
			verticalStackPanel4.Widgets.Add(label20);

			var label21 = new Label();
			label21.Text = "Anxiety meter:";

			var label22 = new Label();
			label22.Text = "#########################--------------------------------------------------------" +
    "-------------------";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 2;
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			horizontalStackPanel1.Padding = new Thickness(5);
			horizontalStackPanel1.GridRow = 2;
			horizontalStackPanel1.GridColumnSpan = 3;
			horizontalStackPanel1.Background = new SolidBrush("#000000AA");
			horizontalStackPanel1.Widgets.Add(label21);
			horizontalStackPanel1.Widgets.Add(label22);

			
			Padding = new Thickness(15, 15, 15, 5);
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(verticalStackPanel2);
			Widgets.Add(verticalStackPanel3);
			Widgets.Add(verticalStackPanel4);
			Widgets.Add(horizontalStackPanel1);
		}

		
	}
}
