/* Generated by MyraPad at Sun, 07. 05. 2023 17  :  49  :  21 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace ANXY
{
	partial class PauseMenu: VerticalStackPanel
	{
		private void BuildUI()
		{
			var textButton1 = new TextButton();
			textButton1.Text = "Reset";
			textButton1.Padding = new Thickness(10);

			var textButton2 = new TextButton();
			textButton2.Text = "Controls";
			textButton2.Padding = new Thickness(10);

			var textButton3 = new TextButton();
			textButton3.Text = "Credits";
			textButton3.Padding = new Thickness(10);

			var textButton4 = new TextButton();
			textButton4.Text = "Exit Game";
			textButton4.Padding = new Thickness(10);

			
			Spacing = 10;
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Padding = new Thickness(15);
			Background = new SolidBrush("#FE3930FF");
			Widgets.Add(textButton1);
			Widgets.Add(textButton2);
			Widgets.Add(textButton3);
			Widgets.Add(textButton4);
		}

		
	}
}
